### ISSUE TITLE
Unknown sensor type: 204802

### ISSUE THREAD

**Issue by yoni3210** [custom-components/sensor.mitemp_bt#17]
Hi,

I'm running the lateset version of hassio : 0.103.4.
and i have a lot of errors about the component , every second without stopping. errors from logfile:
2019-12-27 17:03:15 ERROR (SyncWorker_5) [custom_components.mitemp_bt.sensor] Unknown sensor type: 204802
2019-12-27 17:03:15 ERROR (SyncWorker_5) [custom_components.mitemp_bt.sensor] Unknown sensor type: 208D01
2019-12-27 17:03:15 ERROR (SyncWorker_5) [custom_components.mitemp_bt.sensor] Unknown sensor type: 204802
2019-12-27 17:03:15 ERROR (SyncWorker_5) [custom_components.mitemp_bt.sensor] Unknown sensor type: 204802
2019-12-27 17:03:15 ERROR (SyncWorker_5) [custom_components.mitemp_bt.sensor] Unknown sensor type: 208D01
2019-12-27 17:03:15 ERROR (SyncWorker_5) [custom_components.mitemp_bt.sensor] Unknown sensor type: 204802
2019-12-27 17:03:15 ERROR (SyncWorker_5) [custom_components.mitemp_bt.sensor] Unknown sensor type: 204802
2019-12-27 17:03:15 ERROR (SyncWorker_5) [custom_components.mitemp_bt.sensor] Unknown sensor type: 204802
2019-12-27 17:03:15 ERROR (SyncWorker_5) [custom_components.mitemp_bt.sensor] Unknown sensor type: 208D01
2019-12-27 17:03:15 ERROR (SyncWorker_5) [custom_components.mitemp_bt.sensor] Unknown sensor type: 204802
2019-12-27 17:03:15 ERROR (SyncWorker_5) [custom_components.mitemp_bt.sensor] Unknown sensor type: 204802
2019-12-27 17:03:15 ERROR (SyncWorker_5) [custom_components.mitemp_bt.sensor] Unknown sensor type: 204802
2019-12-27 17:03:15 ERROR (SyncWorker_5) [custom_components.mitemp_bt.sensor] Unknown sensor type: 204802
2019-12-27 17:03:15 ERROR (SyncWorker_5) [custom_components.mitemp_bt.sensor] Unknown sensor type: 208D01
2019-12-27 17:03:15 ERROR (SyncWorker_5) [custom_components.mitemp_bt.sensor] Unknown sensor type: 204802
2019-12-27 17:03:15 ERROR (SyncWorker_5) [custom_components.mitemp_bt.sensor] Unknown sensor type: 204802
2019-12-27 17:03:15 ERROR (SyncWorker_5) [custom_components.mitemp_bt.sensor] Unknown sensor type: 204802
2019-12-27 17:03:15 ERROR (SyncWorker_5) [custom_components.mitemp_bt.sensor] Unknown sensor type: 208D01
2019-12-27 17:03:15 ERROR (SyncWorker_5) [custom_components.mitemp_bt.sensor] Unknown sensor type: 204802
2019-12-27 17:03:15 ERROR (SyncWorker_5) [custom_components.mitemp_bt.sensor] Unknown sensor type: 204802
2019-12-27 17:03:15 ERROR (SyncWorker_5) [custom_components.mitemp_bt.sensor] Unknown sensor type: 208D01
2019-12-27 17:03:15 ERROR (SyncWorker_5) [custom_components.mitemp_bt.sensor] Unknown sensor type: 204802
2019-12-27 17:03:15 ERROR (SyncWorker_5) [custom_components.mitemp_bt.sensor] Unknown sensor type: 204802
2019-12-27 17:03:15 ERROR (SyncWorker_5) [custom_components.mitemp_bt.sensor] Unknown sensor type: 204802
2019-12-27 17:03:15 ERROR (SyncWorker_5) [custom_components.mitemp_bt.sensor] Unknown sensor type: 204802
2019-12-27 17:03:15 ERROR (SyncWorker_5) [custom_components.mitemp_bt.sensor] Unknown sensor type: 204802
2019-12-27 17:03:15 ERROR (SyncWorker_5) [custom_components.mitemp_bt.sensor] Unknown sensor type: 208D01
2019-12-27 17:03:15 ERROR (SyncWorker_5) [custom_components.mitemp_bt.sensor] Unknown sensor type: 204802
2019-12-27 17:03:15 ERROR (SyncWorker_5) [custom_components.mitemp_bt.sensor] Unknown sensor type: 204802
2019-12-27 17:03:15 ERROR (SyncWorker_5) [custom_components.mitemp_bt.sensor] Unknown sensor type: 208D01
2019-12-27 17:03:15 ERROR (SyncWorker_5) [custom_components.mitemp_bt.sensor] Unknown sensor type: 204802
2019-12-27 17:03:15 ERROR (SyncWorker_5) [custom_components.mitemp_bt.sensor] Unknown sensor type: 204802
2019-12-27 17:03:15 ERROR (SyncWorker_5) [custom_components.mitemp_bt.sensor] Unknown sensor type: 208D01
2019-12-27 17:03:15 ERROR (SyncWorker_5) [custom_components.mitemp_bt.sensor] Unknown sensor type: 204802
2019-12-27 17:03:15 ERROR (SyncWorker_5) [custom_components.mitemp_bt.sensor] Unknown sensor type: 204802

I get data from sensors with any issue, expect the errors which increasing the log file constantly.

i've installed the commpents using HACS , i have installed the latets version : Installed: 0.4.0.

in the configuration.yaml i've only have the following configuration : 
sensor:
  - platform: mitemp_bt

Any idea?

**Comment by Magalex2x14** [comment]
What xiaomi-sensors (devices) do you use (among those that are not supported by our component)? Added this message to the code, since it most likely indicates the possibility of implementing the support of such sensors by our component.
Now I understand that this was not a good idea, since, indeed, the log will be spammed...
That is, this message does not mean that something is wrong. It reports on the reception of broadcast packets from devices whose support is not implemented in the component.
Most likely tomorrow I will be able to publish a release addressing the issue of filling out the log.

**Comment by Magalex2x14** [comment]
As a temporary workaround you can [change logging level](https://www.home-assistant.io/integrations/logger/) for the component.
For example (configuration.yaml):
```yaml
logger:
  default: warn
  logs:
    custom_components.mitemp_bt: critical
```

**Comment by yoni3210** [comment]
Thank you, I'll wait for fix tomorrow.

**Comment by aabeijon** [comment]
I have the same issue. Let me know if you need any outputs from the hcitool from us.
I live in a big building where there are a lot of BLE devices everywhere from other apartments.

```
2019-12-27 19:31:25 ERROR (SyncWorker_1) [custom_components.mitemp_bt.sensor] Unknown sensor type: 20AADA
2019-12-27 19:37:38 ERROR (SyncWorker_1) [custom_components.mitemp_bt.sensor] Unknown sensor type: 20AAA5
2019-12-27 19:37:38 ERROR (SyncWorker_1) [custom_components.mitemp_bt.sensor] Unknown sensor type: 20AABE
2019-12-27 19:47:43 ERROR (SyncWorker_15) [custom_components.mitemp_bt.sensor] Unknown sensor type: 20AAEC
2019-12-27 19:51:50 ERROR (SyncWorker_14) [custom_components.mitemp_bt.sensor] Unknown sensor type: 20AA37
2019-12-27 19:51:50 ERROR (SyncWorker_14) [custom_components.mitemp_bt.sensor] Unknown sensor type: 20AA65
2019-12-27 19:57:53 ERROR (SyncWorker_14) [custom_components.mitemp_bt.sensor] Unknown sensor type: 20AAF5
2019-12-27 19:57:53 ERROR (SyncWorker_14) [custom_components.mitemp_bt.sensor] Unknown sensor type: 20AA13
2019-12-27 20:01:55 ERROR (SyncWorker_19) [custom_components.mitemp_bt.sensor] Unknown sensor type: 20AA9A
2019-12-27 20:03:56 ERROR (SyncWorker_3) [custom_components.mitemp_bt.sensor] Unknown sensor type: 20AAA6
2019-12-27 20:03:56 ERROR (SyncWorker_3) [custom_components.mitemp_bt.sensor] Unknown sensor type: 20AACB
2019-12-27 20:10:07 ERROR (SyncWorker_19) [custom_components.mitemp_bt.sensor] Unknown sensor type: 20AA89
```

**Comment by Magalex2x14** [comment]
@aabeijon if it’s not difficult for you, do a one minute dump. You have more variety of codes. Just to satisfy curiosity and to check that this is not the result of some kind of bug:
```shell
sudo hcidump --raw hci > dump.txt
```
Just run the specified command, and the resulting dump.txt can be placed somewhere and give a link.

**Comment by aabeijon** [comment]
Sure thing @Magalex2x14 
I've attached it to the post and its on my google drive. 

[HCI Dump.zip](https://github.com/custom-components/sensor.mitemp_bt/files/4006422/HCI.Dump.zip)

https://drive.google.com/file/d/1okm5A5FGaYT8dHiV3NR0AQxU4oYRxeuh/view?usp=sharing

**Comment by Magalex2x14** [comment]
Ok, guys, here is fixed 0.4.1 release. Please update.

**Comment by yoni3210** [comment]
Checked, still the same issue:
2019-12-28 09:18:16 ERROR (SyncWorker_7) [custom_components.mitemp_bt.sensor] Unknown sensor type: 204802
2019-12-28 09:18:16 ERROR (SyncWorker_7) [custom_components.mitemp_bt.sensor] Unknown sensor type: 204802
2019-12-28 09:18:16 ERROR (SyncWorker_7) [custom_components.mitemp_bt.sensor] Unknown sensor type: 208D01
2019-12-28 09:18:16 ERROR (SyncWorker_7) [custom_components.mitemp_bt.sensor] Unknown sensor type: 204802
2019-12-28 09:18:16 ERROR (SyncWorker_7) [custom_components.mitemp_bt.sensor] Unknown sensor type: 204802
2019-12-28 09:18:16 ERROR (SyncWorker_7) [custom_components.mitemp_bt.sensor] Unknown sensor type: 204802
2019-12-28 09:18:16 ERROR (SyncWorker_7) [custom_components.mitemp_bt.sensor] Unknown sensor type: 208D01
2019-12-28 09:18:16 ERROR (SyncWorker_7) [custom_components.mitemp_bt.sensor] Unknown sensor type: 204802
2019-12-28 09:18:16 ERROR (SyncWorker_7) [custom_components.mitemp_bt.sensor] Unknown sensor type: 204802
2019-12-28 09:18:16 ERROR (SyncWorker_7) [custom_components.mitemp_bt.sensor] Unknown sensor type: 208D01
2019-12-28 09:18:16 ERROR (SyncWorker_7) [custom_components.mitemp_bt.sensor] Unknown sensor type: 204802
2019-12-28 09:18:16 ERROR (SyncWorker_7) [custom_components.mitemp_bt.sensor] Unknown sensor type: 204802
2019-12-28 09:18:16 ERROR (SyncWorker_7) [custom_components.mitemp_bt.sensor] Unknown sensor type: 204802
2019-12-28 09:18:16 ERROR (SyncWorker_7) [custom_components.mitemp_bt.sensor] Unknown sensor type: 208D01
2019-12-28 09:18:16 ERROR (SyncWorker_7) [custom_components.mitemp_bt.sensor] Unknown sensor type: 204802
2019-12-28 09:18:16 ERROR (SyncWorker_7) [custom_components.mitemp_bt.sensor] Unknown sensor type: 204802
2019-12-28 09:18:16 ERROR (SyncWorker_7) [custom_components.mitemp_bt.sensor] Unknown sensor type: 208D01
2019-12-28 09:18:16 ERROR (SyncWorker_7) [custom_components.mitemp_bt.sensor] Unknown sensor type: 204802
2019-12-28 09:18:16 ERROR (SyncWorker_7) [custom_components.mitemp_bt.sensor] Unknown sensor type: 204802
2019-12-28 09:18:16 ERROR (SyncWorker_7) [custom_components.mitemp_bt.sensor] Unknown sensor type: 204802
2019-12-28 09:18:16 ERROR (SyncWorker_7) [custom_components.mitemp_bt.sensor] Unknown sensor type: 208D01
2019-12-28 09:18:16 ERROR (SyncWorker_7) [custom_components.mitemp_bt.sensor] Unknown sensor type: 204802
2019-12-28 09:18:16 ERROR (SyncWorker_7) [custom_components.mitemp_bt.sensor] Unknown sensor type: 204802
2019-12-28 09:18:16 ERROR (SyncWorker_7) [custom_components.mitemp_bt.sensor] Unknown sensor type: 204802

**Comment by Magalex2x14** [comment]
@yoni3210 Recheck, please, whether the component is really updated. Sometimes I also encounter a problem in HACS when I have to go to the updated component page and manually select the required version in the drop-down list, and only then the component is really updated.
